plugins {
    id 'com.android.application'
}

static def versionCodeEpoch() {
    return (new Date().getTime() / 1000).toInteger()
}

def gitCommit = { ->
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine 'git', 'rev-parse', '--short=7', 'HEAD'
        standardOutput = stdout
    }
    return stdout.toString().trim()
}

android {
    namespace 'net.taler.donauverificator'
    compileSdkVersion 36

    defaultConfig {
        applicationId "net.taler.donauverificator"
        minSdk 30
        targetSdk 36
        versionCode 2
        versionName "1.1.0"

        buildConfigField "boolean", "ENABLE_DEVELOPER_MODE", "true"
        buildConfigField "boolean", "ALLOW_INSECURE_HTTP", "true"
        manifestPlaceholders = [usesCleartextTraffic: "true"]

        archivesBaseName = "donau-verificator"
        externalNativeBuild {
            cmake {
                cppFlags ''
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            // inherit defaults; specific behavior controlled via product flavors
        }
    }

    flavorDimensions = ["distributionChannel"]
    productFlavors {
        fdroid {
            dimension "distributionChannel"
            applicationIdSuffix ".fdroid"
        }

        nightly {
            dimension "distributionChannel"
            applicationIdSuffix ".nightly"
            versionCode versionCodeEpoch()
            versionNameSuffix " ($gitCommit)"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
        prefab true
        buildConfig true
    }

    packagingOptions {
        // Exclude specific files or directories that might cause conflicts
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/*.kotlin_module'

        // Merge specific files if needed
        merge 'META-INF/LGPL2.1'
        merge 'META-INF/AL2.0'

        // Exclude everything under META-INF to avoid conflicts
        resources.excludes.add("META-INF/**/*")
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    splits {
        abi {
            // can not be defined per flavor, so we use a property to turn this on for F-Droid
            enable project.hasProperty('splitApk')
            reset() // Resets the list of ABIs to remove all included by default
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            universalApk false
        }
    }

    lint {
        abortOnError true
        ignoreWarnings false
    }
}

dependencies {
    // TODO: do not vendor pre-built libsodium
    implementation fileTree(dir: 'src/main/libs/', include: ['libsodium-1.0.19.0.aar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.4'
    implementation 'androidx.navigation:navigation-fragment:2.9.5'
    implementation 'androidx.navigation:navigation-ui:2.9.5'
    implementation 'com.github.yuriy-budiyev:code-scanner:2.3.2'
    // https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
    implementation group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.70'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.preference:preference:1.2.1'
}
